### ISSUE TITLE
Useless patch left in the layer

### ISSUE THREAD

**Issue by FlorentRevest** [Pelagicore/meta-pelux#143]
I'm a bit confused by the existence of: layers/poky/patch/0001-Fix-automated-runtime-testing-using-SystemdbootTarge.patch
It looks like the patch doesn't apply on top of poky anymore and I have been able to run automated tests without using this patch. Does anyone know if it's necessary for anything? Should we re-work this patch or remove it?

**Comment by GordanM** [comment]
Hey Florent, this patch was sent to upstream a while back by @erikboto, I believe if the patch doesn't apply anymore and the test are able to run on the target w/o it then this temp patch should be removed. Erik what are your thoughts about this?

Thanks!
