### ISSUE TITLE
qtapplicationmanager.bbappend: libsoftwarecontainer-plugin breaks the nativesdk build

### ISSUE THREAD

**Issue by GordanM** [Pelagicore/meta-pelux#21]
The nativesdk build is broken as the bbappend assumes that the examples are built even for the `-config tools-only` version. 

Furthermore, I am questioning whether this bbappend should be included in PELUX by default. This plugin was made as an example implementation by Robert and I am not sure would it be sensible to use it as a project would need to create it's own variant as far as I know. Please discuss :)

**Comment by rpannek** [comment]
I guess we still want to have the plugin example installed on the image so we can showcase the SC integration with Appman.

**Comment by GordanM** [comment]
Fixed with #24 .
