### ISSUE TITLE
[Q] appman-controller

### ISSUE THREAD

**Issue by sparkleholic** [Pelagicore/meta-pelux#240]
I do not know if this is the right place to leave a question.
If the right place exists separately, please let me know.

The question is that whether I can use `appman-controller` command on the pelux.

I just tried to list the installed apps up by the following command, but it failed with an error.
```
$ appman-controller list-applications

ERROR: Could not find the D-Bus interface of a running Application-Manager instance.
(did you start the appman with '--dbus none'?
```
appman seems to be working fine, which connects to the dbus session bus.
```
207 root       0:13 /usr/bin/appman -r -c am-config.yaml --dbus session -platform eglfs -c /opt/am/sc-config.yaml
```
To check `DBUS_SESSION_BUS_ADDRESS`
```
$ strings /proc/207/environ 
PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INVOCATION_ID
0e4c592333ac4531aa6a65b67dc16f02
JOURNAL_STREAM
8:7050
HOME
/home/root/
LC_ALL
en_US
DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/root/dbus/user_bus_socket
QT_IM_MODULE
qtvirtualkeyboard
XDG_RUNTIME_DIR
/tmp
QT_WAYLAND_HARDWARE_INTEGRATION
brcm
```

I tried by setting `DBUS_SESSION_BUS_ADDRESS` env variable, but the result was the same as before.
```
$ export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/root/dbus/user_bus_socke"
$ appman-controller list-applications

ERROR: Could not find the D-Bus interface of a running Application-Manager instance.
(did you start the appman with '--dbus none'?
```

**Comment by Gagi2k** [comment]
Hi,

with exporting the session bus address it should work. Looking at your command, it looks like you are missing a 't' at the end in the session bus address ?

**Comment by sparkleholic** [comment]
Such a basic mistake ..!
Sorry for the confusion. 
Thanks!
