### ISSUE TITLE
Change default install path from /opt to ~/sdk

### ISSUE THREAD

**Issue by rpannek** [Pelagicore/meta-pelux#25]
Most of the users which install the SDK haven't prepared their system to allow the user to install things into /opt. /opt is the default install path for the SDK but should be changed to ~/sdk

**Comment by GordanM** [comment]
Could be changed somewhere around here: 

https://github.com/openembedded/openembedded-core/blob/master/meta/files/toolchain-shar-extract.sh#L143
https://github.com/openembedded/openembedded-core/blob/master/meta/files/toolchain-shar-extract.sh#L58

I guess the SDKPATH variable could be changed somehow.

**Comment by GordanM** [comment]
It is not feasible you will encounter build failures: 

For instance: gcc-crosssdk-initial_6.2.bb:do_compile
`configure: error: --with-native-system-header-dir argument ~/sdk/poky/2.2.1/sysroots/x86_64-pokysdk-linux/usr/include must be an absolute directory`

**Comment by GordanM** [comment]
Won't fix.
