### ISSUE TITLE
[Q] Qt Creator version & wayland RPI image

### ISSUE THREAD

**Issue by Shazter** [Pelagicore/meta-pelux#255]
1.
I try to use the Pelux 3.0 SDK for Raspberry Pi3, based on the documentation https://pelux.io/software-factory/master/swf-blueprint/docs/articles/sdk/configure-qtcreator.html

Installation process was understandable and successful, but the following points I cannot execute shown here: https://stackoverflow.com/questions/54810715/setup-pelux-3-0-raspberry-pi-3-kit-qtcreator-cmake-error-unknown-option

2. 
I saw RPI image is forced to single process of neptune ui 3 and when  I connect through ssh to RPI, then I see only one process in top. 

1. Is Wayland active?
2. How I can confirm, that wayland is active?

**Comment by Shazter** [comment]
3. 
Please let me ask one more question. When I have installed the Pelux SDK, then I'm able to modifiy/extend the Neptune 3 UI (HMI Apps), without license of QtAutomotive suite?

**Comment by sashko** [comment]
> Please let me ask one more question. When I have installed the Pelux SDK, then I'm able to modifiy/extend the Neptune 3 UI (HMI Apps), without license of QtAutomotive suite?

Neptune 3 UI is licensed under GPLv3, so yes - you can modify it as long as you obey the license.

**Comment by Shazter** [comment]
Thank you for confirmation @sashko 
Sorry I figured out the handbook has his own repo. I will raise a bug there, because I found some issue too

**Comment by sashko** [comment]
@Shazter could you please confirm whether or not this issue has been fixed by cleaning up the documentation?
