### ISSUE TITLE
Remove dependency on boot2qt

### ISSUE THREAD

**Issue by jonte** [Pelagicore/meta-pelux#31]
The bbappends in recipes-qt/automotive introduce a dependency to boo2qt.

You can't build w/o the dangling bbappends option enabled. - Can we move these bbappends somewhere else, or include them in the layer only when the boot2qt layer is enabled?

**Comment by DunderRoffe** [comment]
I think we should consider having a "meta-pelux-qt" layer where these bbappends could reside. That would make it possible to also remove all qt dependencies from the pelux-base.xml manifest

**Comment by GordanM** [comment]
@jonte I would have to investigate a bit but as far as I know the solution could be similar to what has been done in meta-bistro. Meaning, we separate these bbappends (softwarecontainer and Qt Auto specific) into layer directories and the recipes and appends are only active if the original layer is a part of the build.

For reference take a look at: 
* https://github.com/Pelagicore/meta-bistro/blob/master/README.md#layers
* https://github.com/Pelagicore/meta-bistro/blob/master/conf/layer.conf#L28

**Comment by jonte** [comment]
@GordanM Thanks for your input! I will see if I can have myself or a team member help out with this issue. Cheers!

**Comment by tobsan** [comment]
I'll start work on this right now.

**Comment by tobsan** [comment]
Closed through #41
