### ISSUE TITLE
Remove dependency on meta-template

### ISSUE THREAD

**Issue by jonte** [Pelagicore/meta-pelux#32]
I don't think it should be a required layer for all PELUX-based projects, since the template-service provided might not be used by all projects.

Dependency introduced here:

https://github.com/Pelagicore/meta-pelux/blob/3b80b2bb6effe524577dde63c26081bb75a95df8/recipes-core/images/core-image-pelux.bb#L15

**Comment by GordanM** [comment]
@jonte thanks for brining this up. I would like to initiate an offline discussion with you, @rpannek and @breakreturn. After we reach an agreement we can decide on the next steps on this issue.

**Comment by tobsan** [comment]
Perhaps this could be moved from the pelux bbclass into the pelux-minimal image?

**Comment by jonte** [comment]
Should i be a part of a *minimal* image, though? Maybe even a minimal system can do without this?

I do agree that it should not be in the bbclass.
