### ISSUE TITLE
Make softwarecontainer optional by using a distro feature

### ISSUE THREAD

**Issue by jonte** [Pelagicore/meta-pelux#33]
By making a distro feature for softwarecontainer, and thus making it optional for inclusion, we no longer have to rely on meta-virtualization. meta-virtualization depends on meta-python, meta-filesystems and meta-networking - so we would remove 4 required layers for PELUX users not needing softwarecontainer if we make it optional.

Current softwarecontainer inclusion is here:

https://github.com/Pelagicore/meta-pelux/blob/3b80b2bb6effe524577dde63c26081bb75a95df8/recipes-core/images/core-image-pelux.bb#L11

**Comment by GordanM** [comment]
@jonte valid remark. Possibly the issue is somewhat connect to the restructuring needed for #31 .
