### ISSUE TITLE
module "QZXing" is not installed in qml @ pelagicore/meta-pelux

### ISSUE THREAD

**Issue by TM9412** [Pelagicore/meta-pelux#96]

**Comment by GordanM** [comment]
Hello @TM9412 and thanks for your contribution. Could you give a bit more context on what are you trying to include in the target image. Is it the barcode processing library QZXing (https://github.com/ftylitak/qzxing)? Can you explain what modifications did you make to produce the error?

**Comment by TM9412** [comment]
Hey Hi, @GordanM 

I am trying to include QR-code feature in this meta-pelux so for that i added this [library QZxing](https://github.com/ftylitak/qzxing/issues/72) and when i run my project it is showing 

**warning**  : QML Image: Invalid image provider: image://qzxing/encode/ 

and i am not get the qrcode so i added import QZXing 2.3 but i get this error in run time
**error** : module "QZXing" is not installed

**Comment by GordanM** [comment]
@TM9412 the "QZxing" library has to be installed on the target image if you would like to use. Have you done this modification to the target image? 

This would usually include creating a Yocto recipe that compiles/includes this QML module to the target image.

**Comment by TM9412** [comment]
Hi @GordanM 
 I have done this modification [](https://github.com/ftylitak/qzxing/issues/72) 

How to installed "QZxing" library on the target image  ?

**Comment by GordanM** [comment]
@TM9412 you would need to create a Yocto recipe that installs the required libraries to the system and include the component in the target image. Do you have experience with Yocto/OpenEmbedded?

I've found a really old example of a Yocto recipe for "QZxing": https://github.com/nickdademo/meta-nickdademo/blob/master/qzxing/qzxing_1.3.bb. Maybe you could create a new recipe based on it? Our platform currently doesn't have an intention in being the holding layer of that component as we are not using it currently. But you could always add another layer to our base platform and use it just in your project.

I would recommend to ask the maintainer of the "QZxing" library to provide you with some support in creating the Yocto recipe, as he would be the best person to ask about "how to" and "where to" install the component on the target image. It might be possible that she/he has done it before as well.

**Comment by GordanM** [comment]
@TM9412 if you need more information on how to use and extend PELUX you can always refer to the documentation in the Software Factory (http://pelux.io/software-factory/master/). It should give you a nice starting point and explanation on how to use the base platform and extend it with your components.

For example, here is an extract how to add your new layer to the project: http://pelux.io/software-factory/master/swf-blueprint/docs/articles/baseplatform/creating-a-new-layer.html 

and here is an example how to structure and create a Yocto recipe using the template C++ service as a base: http://pelux.io/software-factory/master/swf-blueprint/docs/articles/templates/index.html

**Comment by GordanM** [comment]
Closing this issue as it is outside of the context. Feel free to open another issue when you get more progress, we'd be happy to help then.
